# Generated by Django 5.0.2 on 2024-03-04 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='decription',
            new_name='description',
        ),
    ]
